title = "Northern Ireland Developer Conference"
baseurl = "/"
languageCode = "en-us"
theme = "nidevconf"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[markup.goldmark.renderer]
  unsafe = true

[params]
  year = "2021"
  bookingurl = "https://ti.to/nidc/nidc2021"
  cfpurl = "https://sessionize.com/northern-ireland-developer-conference-2021/"
