[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.83.1"

[[redirects]]
  from = "https://nidevconf.netlify.com/*"
  to = "https://www.nidevconf.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/mailing-list*"
  to = "/newsletter/"
  status = 301
  force = true

[[redirects]]
  from = "/tickets/"
  to = "https://ti.to/nidc/nidc2022"
  status = 302
  force = true

[[redirects]]
  from = "/cfp/"
  to = "https://sessionize.com/nidc2022"
  status = 302
  force = true

[[redirects]]
  from = "/venue/"
  to = "https://www.iccbelfast.com/visitor#getting-to-icc-belfast"
  status = 302
  force = true

[[redirects]]
  from = "/data/ni-tech-meetups.ics"
  to = "https://nidc.blob.core.windows.net/public/ni-tech-meetups.ics"
  status = 200

[[redirects]]
  from = "/data/ni-tech-meetups.json"
  to = "https://nidc.blob.core.windows.net/public/ni-tech-meetups.json"
  status = 200
