[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.83.1"

[[redirects]]
  from = "/mailing-list*"
  to = "/newsletter/"
  status = 301
  force = true

[[redirects]]
  from = "/venue/"
  to = "https://www.thealexhotel.ie/find-us/"
  status = 302
  force = true

[[redirects]]
  from = "/tickets/"
  to = "https://www.eventbrite.ie/e/national-open-source-innovation-summit-2025-tickets-1082435336229?aff=oddtdtcreator"
  status = 302
  force = true
